FROM node:22-alpine

WORKDIR /app

COPY apps/web/package.json ./
COPY apps/web/package-lock.json ./
COPY apps/web/svelte.config.js ./
COPY apps/web/vite.config.ts ./
COPY apps/web/tsconfig.json ./
COPY apps/web/postcss.config.cjs ./
COPY apps/web/tailwind.config.ts ./
COPY apps/web/static ./static
COPY apps/web/src ./src

RUN npm ci
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["node", "build"]
